services:
  - type: web
    name: bocra-api
    runtime: docker
    branch: feature/Backend-hosting
    envVars:
      - key: APP_ENV
        value: production
    preDeployCommand: php artisan migrate --force
